### ISSUE TITLE
feature request: permission challenges

### ISSUE THREAD

**Issue by Treppenhaus** [uskyblock/uSkyBlock#28]
__This is a Feature Request__

A challenge type where the player needs a certain permission to complete the challenge.
This would allow for easy integration with other plugins and would allow to create unique challenges easily.

example configuration in challenges.yml:
```yaml
cobblestonegenerator:
        name: '&7Cobble Stone Generator'
        description: Mine from a cobblestone generator.
        type: PERMISSION # <----------
        permission: "uskyblock.challenge.example.perm" # <----------
        # 'cobblestonegenerator.requiredItems' is gone
        displayItem: COBBLESTONE
        lockedDisplayItem: GRAY_STAINED_GLASS_PANE
        resetInHours: 12
        reward:
          text: 3 leather, 20% chance to get a book
          items:
          - LEATHER:3
          - '{p=0.2}BOOK:1'
          currency: 10
          xp: 10
          commands:
          - op:effect give {player} regeneration
        repeatReward:
          text: 1 leather, 10% chance to get a book
          items:
          - LEATHER:1
          - '{p=0.1}BOOK:1'
          currency: 5
          xp: 5
```

I will try to do actually do it myself
