### ISSUE TITLE
Configurable Biome GUI

### ISSUE THREAD

**Issue by marcbal** [uskyblock/uSkyBlock#74]
**Is your feature request related to a problem? Please describe.**
When creating new challenge, we have the ability to give players the ability to set the island’s biome. Players can set the biome using the command `/is biome <biome>` (when they have the permission), but they may not being aware of the availability of the biome when they use the biome GUI.

**Describe the solution you'd like**
Have the ability to configure the list of biomes available in the biome GUI. For instance, a config file (or section in existing file) would look like this:
```yml
biome-gui:
  ocean: # use the key of the biome, like the one given by Biome.getKet().getKey()
    displayItem: tropical_fish
    description: "The ocean biome is the basic..."
  forest:
    displayItem: spruce_sapling
    description: "The forest biome will allow..."
```

**Describe alternatives you've considered**
Manually add new biomes to the GUI in the code of the plugin.

**Additional context**
Would help solving issues #39 and partially #40
